import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { PublicPage } from '../../components/ui/public-page';
import { Button } from '../../components/ui/button';
import { apiClient } from '../../services/apiClient';
export const ContactPage: React.FC = () => {
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [message, setMessage] = useState(''); const [consent, setConsent] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [reference, setReference] = useState('');
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { const result = await apiClient.contact({ name: name.trim(), email: email.trim(), message: message.trim(), consent }); setReference(result.reference); } catch (e) { setError(e instanceof Error ? e.message : 'Could not save your request. Please try again.'); } finally { setBusy(false); } }
  return <PublicPage title="Let's talk about your fields." intro="Ask about a pilot, organization access, or help with your account."><div className="contact-layout"><aside><h2>Start a conversation.</h2><p>Tell us what you are trying to do and how the team can help. Your request will be saved in the platform inbox.</p><p>For organization or expert access, you can also <Link to="/onboarding">submit an application</Link>.</p></aside><section className="workspace-panel">{reference ? <div role="status"><h2>Your request is saved.</h2><p>Keep this reference for follow-up:</p><p className="request-reference">{reference}</p><p>The Rakshak team can review your request in its inbox. No automatic email confirmation is sent.</p><Button variant="secondary" onClick={() => { setReference(''); setMessage(''); }}>Write another request</Button></div> : <form className="workspace-form" onSubmit={submit}><label>Your name<input required maxLength={255} autoComplete="name" value={name} onChange={e => setName(e.target.value)} /></label><label>Email address<input type="email" required maxLength={320} autoComplete="email" value={email} onChange={e => setEmail(e.target.value)} /></label><label>How can we help?<textarea required minLength={10} maxLength={5000} value={message} onChange={e => setMessage(e.target.value)} /></label><label className="consent-control"><input type="checkbox" required checked={consent} onChange={e => setConsent(e.target.checked)} /><span>I agree to using these details to handle this request. <Link to="/privacy">Privacy notice</Link></span></label>{error && <p role="alert" className="message error">{error}</p>}<Button busy={busy} disabled={!consent}>{busy ? 'Saving request…' : 'Submit request'}</Button></form>}</section></div></PublicPage>;
};
