import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, ArrowUpRight, Camera, Check, ClipboardCheck, Layers3, Leaf, ScanLine, ShieldCheck, Smartphone, Sprout } from 'lucide-react';
import { PublicNavbar } from '../../components/layout/PublicNavbar';
import { PublicFooter } from '../../components/layout/PublicFooter';
import { Button } from '../../components/ui/button';
import { Accordion } from '../../components/ui/accordion';

const questions = [
  { question: 'Who is Rakshak AI for?', answer: 'Farmers use the mobile app to record soybean crops and revisit evidence. Organizations use the web workspace to organize field records. Agronomists review requested cases, and administrators manage access.' },
  { question: 'Is the result a confirmed diagnosis?', answer: 'No. The pilot selects useful observations and returns a visual indication with supporting frames. The supplied models are an unvalidated baseline. Consult an agronomist before acting on uncertain symptoms.' },
  { question: 'Can I use it without a connection?', answer: 'You can record a video with your phone and choose it later. Uploading, analysis and viewing saved records require a connection. A failed processing job can be retried from the saved scan.' },
  { question: 'Is my evidence private?', answer: 'Authorized accounts can access their own evidence. A requested review shares that case with an agronomist. Future training permission is optional and separate from processing consent.' },
];

export const LandingPage: React.FC = () => <div className="brand-page premium-landing"><PublicNavbar/><main id="main-content">
  <section className="launch-hero"><div className="launch-copy"><p className="launch-kicker"><span/> FIELD INTELLIGENCE. HUMAN PERSPECTIVE.</p><h1>Closer to your crop.<br/><em>Clearer together.</em></h1><p className="launch-description">From a farmer's phone to an expert's workspace. Turn short soybean videos into evidence your whole field team can act on.</p><div className="hero-actions"><Button asChild><Link to="/apply/organization">Bring your team <ArrowUpRight size={18}/></Link></Button><Link className="quiet-link" to="/for-farmers"><Smartphone size={18}/> Explore the farmer app</Link></div><div className="launch-principles"><span><ShieldCheck size={16}/> Private field records</span><span><ClipboardCheck size={16}/> Human review</span></div></div>
  <div className="launch-visual"><img className="launch-foliage" src="/soybean-field.png" alt="Illustrative soybean foliage" fetchPriority="high"/><div className="phone-preview" aria-label="Illustration of the mobile recording workflow"><div className="phone-toolbar"><Sprout size={19}/><strong>Rakshak AI</strong><span>APP PREVIEW</span></div><h2>Your fields,<br/>in focus.</h2><div className="phone-capture"><Camera size={24}/><strong>Take a closer look.</strong><p>A short video. Several plants.<br/>One useful field record.</p><span>Record a scan <ArrowRight size={15}/></span></div><div className="phone-step"><span>01</span><div><strong>Choose your field</strong><small>Every observation, in its place</small></div></div><div className="phone-step"><span>02</span><div><strong>Capture the evidence</strong><small>10–30 seconds in even daylight</small></div></div></div><div className="visual-caption"><ScanLine size={19}/><span>Built for the field.<br/><strong>Connected to your team.</strong></span></div></div></section>
  <div className="launch-strip"><p>ONE CONNECTED FIELD RECORD</p><span>Farmer app <Smartphone/></span><span>Organization workspace <Layers3/></span><span>Agronomist review <ClipboardCheck/></span></div>
  <section className="launch-section product-story"><header><p className="section-label">LESS GUESSWORK. MORE CONTEXT.</p><h2>Good decisions start<br/>with a closer look.</h2><p>Keep the original observations alongside the interpretation. Give farmers and field teams a shared place to start.</p></header><div className="product-story-grid"><article className="story-dark"><ScanLine size={28}/><h3>Evidence before conclusions.</h3><p>Useful frames, the original video, and a clear explanation. See what informed the result before deciding your next step.</p><div className="story-evidence"><img src="/soybean-field.png" alt="Illustrative close view of soybean leaves" loading="lazy"/><span>Capture → Observe → Review</span></div></article><article className="story-light"><ClipboardCheck size={28}/><h3>Expertise stays in the loop.</h3><p>Request an agronomist's independent assessment. Their observations and next steps return to the farmer's saved report.</p><ol className="review-illustration"><li><Check/> Farmer records a concern</li><li><Check/> Expert inspects the evidence</li><li><Check/> Review stays with the field</li></ol><Link to="/apply/agronomist">Join as an agronomist <ArrowUpRight size={18}/></Link></article></div></section>
  <section className="team-section"><div><p className="section-label">YOUR OPERATIONS, IN ONE VIEW</p><h2>The field team<br/>has a home.</h2><p>Move from scattered observations to organized field records. Find the latest scans, review uncertain results and keep your own farms in view.</p><ul>{['Organization-scoped farms and evidence', 'Filterable reports and CSV exports', 'Reviewed access for your team'].map(item=><li key={item}><Check size={18}/>{item}</li>)}</ul><Button asChild><Link to="/apply/organization">Create an organization workspace <ArrowRight size={18}/></Link></Button></div><div className="workspace-illustration" aria-label="Illustrative workflow, not customer data"><div className="illustration-top"><Sprout size={20}/><span>Organization overview</span><small>WORKFLOW PREVIEW</small></div><div className="illustration-title"><h3>From a field,<br/>to a clear next step.</h3><Leaf size={35}/></div><div className="illustration-grid">{[{icon:Camera,title:'Capture',text:'Keep the original video'},{icon:Layers3,title:'Organize',text:'Group records by field'},{icon:ClipboardCheck,title:'Review',text:'Add an expert assessment'},{icon:ShieldCheck,title:'Control',text:'Share with authorized people'}].map(({icon:Icon,title,text})=><div key={title}><Icon/><strong>{title}</strong><span>{text}</span></div>)}</div><Link to="/pricing">Explore organization plans <ArrowUpRight size={17}/></Link></div></section>
  <section className="launch-section mobile-story"><div className="mobile-story-photo"><img src="/soybean-field.png" alt="Illustrative soybean field" loading="lazy"/><span><Smartphone size={20}/> YOUR PHONE. YOUR FIELD.</span></div><div><p className="section-label">FARMER FIRST. MOBILE FIRST.</p><h2>Your next field visit,<br/>with more perspective.</h2><p>Record a concern while you're in the field. Come back to the evidence, follow the next steps and ask for a second opinion when you need one.</p><div className="mobile-benefits"><span><Camera/> Short video capture</span><span><Layers3/> Saved field history</span><span><ClipboardCheck/> Expert review requests</span></div><Button asChild><Link to="/for-farmers">Meet the farmer app <ArrowUpRight size={18}/></Link></Button><p className="helper-copy">Free during the soybean pilot. Public app-store release is not yet available.</p></div></section>
  <section className="launch-section launch-faq"><div><p className="section-label">A LITTLE MORE CLARITY</p><h2>Before you<br/>step into the field.</h2><Link className="quiet-link" to="/contact">Talk to our team <ArrowUpRight size={18}/></Link></div><Accordion items={questions}/></section>
  <section className="launch-final"><Sprout size={30}/><h2>Better context.<br/>For every field visit.</h2><p>Start with a farmer's observation. Bring the right people into the picture.</p><div className="hero-actions"><Button variant="accent" asChild><Link to="/apply/organization">Start your organization pilot <ArrowUpRight size={18}/></Link></Button><Link to="/pricing">View plans <ArrowRight size={16}/></Link></div></section>
</main><PublicFooter/></div>;
