import React, { useState } from 'react';
import { ArrowUpRight, Check, ChevronRight, CircleDot, FileText, FolderOpen, Leaf, PanelsTopLeft, ScanLine, Search, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
const views = ['Field records', 'Evidence review', 'Team workflow'] as const;
export function WorkspacePreview() {
    const [view, setView] = useState<(typeof views)[number]>('Field records');
    return <div className="showcase-wrap">
    <div className="showcase-selector" role="group" aria-label="Explore the product preview">{views.map((label, index) => <button key={label} aria-pressed={view === label} onClick={() => setView(label)}><span>0{index + 1}</span>{label}</button>)}</div>
    <div className="showcase-window" aria-label="Interactive product illustration, not live customer records">
      <aside className="showcase-rail"><div className="showcase-workspace"><span><Leaf size={17}/></span><strong>Field workspace</strong></div><small>Workspace preview</small><div className="showcase-nav active"><PanelsTopLeft size={15}/>Overview</div><div className="showcase-nav"><FolderOpen size={15}/>Field records</div><div className="showcase-nav"><FileText size={15}/>Assessments</div><div className="showcase-rail-bottom"><ShieldCheck size={15}/><span>Private by design</span></div></aside>
      <div className="showcase-content"><div className="showcase-topline"><span>Workspace <ChevronRight size={12}/>{view}</span><span className="showcase-example">Illustrative preview</span></div><div className="showcase-page-title"><div><p>Soybean field care</p><h2>{view === 'Field records' ? 'The whole picture, in one place.' : view === 'Evidence review' ? 'Look closer. Decide with context.' : 'One record. The right expertise.'}</h2></div><ScanLine size={22}/></div>
      <div className="showcase-split"><div className="showcase-records">{view === 'Field records' ? <><div className="showcase-list-toolbar"><strong>Field records</strong><Search size={14}/></div>{['Capture an observation', 'Keep the original evidence', 'Follow the assessment'].map((text, index) => <div className="showcase-record" key={text}><span className="showcase-record-icon">{index === 0 ? <Leaf size={17}/> : index === 1 ? <ScanLine size={17}/> : <FileText size={17}/>}</span><div><strong>{text}</strong><p>{['A short video from the farmer’s phone', 'Frames and video stay with the field', 'Clear status, context and next steps'][index]}</p></div><ChevronRight size={14}/></div>)}<div className="showcase-record-footer"><CircleDot size={14}/><span>From first capture to expert follow-up</span></div></> : view === 'Evidence review' ? <><div className="showcase-list-toolbar"><strong>Independent review</strong><FileText size={14}/></div><h3>AI suggests.<br />An expert assesses.</h3><p className="showcase-detail-copy">Inspect the original observations, record a correction and return useful next steps to the farmer.</p><div className="showcase-note"><CircleDot size={15}/>Uncertainty stays visible</div></> : <><div className="showcase-list-toolbar"><strong>Connected field care</strong><ShieldCheck size={14}/></div><ol className="showcase-timeline">{['Farmer captures a concern', 'Organization keeps the record', 'Agronomist reviews the evidence', 'Farmer receives the assessment'].map(text => <li key={text}><Check size={14}/><span>{text}</span></li>)}</ol></>}
      </div><div className="showcase-evidence"><div className="showcase-image"><img src="/soybean-field.png" alt="Illustrative soybean crop, not a diagnostic result"/><span><ScanLine size={14}/>A closer view</span></div><div className="showcase-evidence-caption"><span className="showcase-file-icon"><FileText size={18}/></span><div><strong>Every observation has a place.</strong><p>Original video · Selected frames · Review</p></div></div></div></div>
      <div className="showcase-bottom"><span>Evidence and human judgment, connected.</span><Link to="/how-it-works">Explore the workflow <ArrowUpRight size={14}/></Link></div></div>
    </div>
  </div>;
}
