import 'package:flutter/material.dart';
import '../api_client.dart';
import '../core/app_theme.dart';
import '../widgets/app_components.dart';
import 'history_screen.dart';
import 'profile_screen.dart';
import 'report_screens.dart';
import 'scan_screens.dart';

class HomeScreen extends StatefulWidget { const HomeScreen({super.key}); @override State<HomeScreen> createState() => _HomeScreenState(); }
class _HomeScreenState extends State<HomeScreen> {
  int tab = 0;
  @override Widget build(BuildContext context) { final pages = [const DashboardTab(), const ScanHistoryScreen(), const ProfileScreen()]; return Scaffold(body: SafeArea(child: pages[tab]), bottomNavigationBar: NavigationBar(selectedIndex: tab, onDestinationSelected: (value) => setState(() => tab = value), destinations: const [NavigationDestination(icon: Icon(Icons.home_outlined), selectedIcon: Icon(Icons.home_rounded), label: 'Fields'), NavigationDestination(icon: Icon(Icons.history_rounded), label: 'History'), NavigationDestination(icon: Icon(Icons.person_outline_rounded), label: 'Profile')])); }
}

class DashboardTab extends StatefulWidget { const DashboardTab({super.key}); @override State<DashboardTab> createState() => _DashboardTabState(); }
class _DashboardTabState extends State<DashboardTab> {
  late Future<_DashboardData> data;
  @override void initState() { super.initState(); data = _load(); }
  Future<_DashboardData> _load() async { final values = await Future.wait([ApiClient.instance.currentUser(), ApiClient.instance.listFields(), ApiClient.instance.listVideos()]); return _DashboardData(user: values[0] as Map<String, dynamic>, fields: values[1] as List<Map<String, dynamic>>, videos: values[2] as List<Map<String, dynamic>>); }
  @override Widget build(BuildContext context) => FutureBuilder<_DashboardData>(future: data, builder: (context, snapshot) {
    if (snapshot.connectionState != ConnectionState.done) return const Center(child: CircularProgressIndicator());
    if (snapshot.hasError) return PageContent(children: [Text('Your fields', style: Theme.of(context).textTheme.headlineSmall), const SizedBox(height: 16), const AppCard(child: Text('Could not load live field data. Please try again.')), const SizedBox(height: 12), PrimaryAction(label: 'Try again', onPressed: () => setState(() => data = _load()))]);
    final value = snapshot.data!; final latest = <String, Map<String, dynamic>>{};
    for (final video in value.videos) { final fieldId = video['field_id']?.toString(); if (fieldId != null && !latest.containsKey(fieldId)) latest[fieldId] = video; }
    final name = value.user['display_name']?.toString() ?? value.user['email']?.toString() ?? 'there';
    return PageContent(children: [const SizedBox(height: 8), Text('Good to see you, $name', style: Theme.of(context).textTheme.headlineSmall), const SizedBox(height: 6), const Text('Your live field records and scan results.'), const SizedBox(height: 22), AppCard(color: RakshakColors.ink, padding: const EdgeInsets.all(20), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Icon(Icons.eco_rounded, color: RakshakColors.signal, size: 36), const SizedBox(height: 14), Text('${value.fields.length} field${value.fields.length == 1 ? '' : 's'} in your account', style: const TextStyle(color: Colors.white, fontSize: 21, fontWeight: FontWeight.w800)), Text('${value.videos.length} uploaded scan${value.videos.length == 1 ? '' : 's'}', style: const TextStyle(color: Color(0xffc8d5cc)))])), const SizedBox(height: 28), const SectionHeading(title: 'Your fields'), const SizedBox(height: 8), if (value.fields.isEmpty) const EmptyState(icon: Icons.landscape_outlined, title: 'No fields yet', body: 'Create a field through the backend before starting a scan.'), for (final field in value.fields) Padding(padding: const EdgeInsets.only(bottom: 12), child: _FieldCard(field: field, latestVideo: latest[field['id']?.toString()], onTap: () => navigateTo(context, FieldDetailsScreen(field: field, latestVideo: latest[field['id']?.toString()])))), const SizedBox(height: 4), PrimaryAction(label: 'Start a new scan', icon: Icons.add_a_photo_outlined, onPressed: () => navigateTo(context, const NewScanScreen())), const SizedBox(height: 26), const SectionHeading(title: 'Recent scans'), if (value.videos.isEmpty) const Padding(padding: EdgeInsets.only(top: 10), child: Text('No scans have been uploaded yet.')), for (final video in value.videos.take(5)) Padding(padding: const EdgeInsets.only(top: 10), child: _ScanTile(video: video, onTap: () => navigateTo(context, CropHealthReportScreen(videoId: video['video_id']?.toString())))), const SizedBox(height: 18), const SafetyNote()]);
  });
}
class _DashboardData { const _DashboardData({required this.user, required this.fields, required this.videos}); final Map<String, dynamic> user; final List<Map<String, dynamic>> fields, videos; }
class _FieldCard extends StatelessWidget { const _FieldCard({required this.field, required this.latestVideo, required this.onTap}); final Map<String, dynamic> field; final Map<String, dynamic>? latestVideo; final VoidCallback onTap; @override Widget build(BuildContext context) { final status = latestVideo?['status']?.toString() ?? 'No scans yet'; return InkWell(onTap: onTap, borderRadius: BorderRadius.circular(16), child: AppCard(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [Expanded(child: Text(field['name']?.toString() ?? 'Unnamed field', style: Theme.of(context).textTheme.titleMedium)), StatusBadge(label: status, color: status == 'ready' ? RakshakColors.healthy : RakshakColors.warning, textColor: RakshakColors.ink)]), Text(field['crop_id']?.toString() ?? 'Crop not set'), const SizedBox(height: 10), Text(field['area_hectares'] == null ? 'Area not recorded' : '${field['area_hectares']} hectares'), const SizedBox(height: 10), const Text('Health score is unavailable until the validated scoring API is enabled.')]))); } }
class _ScanTile extends StatelessWidget { const _ScanTile({required this.video, required this.onTap}); final Map<String, dynamic> video; final VoidCallback onTap; @override Widget build(BuildContext context) => InkWell(onTap: onTap, child: AppCard(child: Row(children: [const Icon(Icons.analytics_outlined, color: RakshakColors.leaf), const SizedBox(width: 12), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(video['status']?.toString() ?? 'Scan', style: Theme.of(context).textTheme.titleMedium), Text('Uploaded ${video['created_at'] ?? '—'}')]))]))); }
class FieldDetailsScreen extends StatelessWidget { const FieldDetailsScreen({super.key, required this.field, this.latestVideo}); final Map<String, dynamic> field; final Map<String, dynamic>? latestVideo; @override Widget build(BuildContext context) => AppPage(title: field['name']?.toString() ?? 'Field', onBack: () => Navigator.pop(context), child: PageContent(children: [AppCard(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(field['name']?.toString() ?? 'Unnamed field', style: Theme.of(context).textTheme.headlineSmall), Text(field['crop_id']?.toString() ?? 'Crop not set'), const SizedBox(height: 8), Text(field['area_hectares'] == null ? 'Area not recorded' : '${field['area_hectares']} hectares')])), const SizedBox(height: 24), const SectionHeading(title: 'Latest scan'), const SizedBox(height: 8), AppCard(child: Text(latestVideo == null ? 'No scan has been uploaded for this field.' : 'Status: ${latestVideo!['status']}')), if (latestVideo != null) ...[const SizedBox(height: 16), PrimaryAction(label: 'View latest report', onPressed: () => navigateTo(context, CropHealthReportScreen(videoId: latestVideo!['video_id']?.toString())))], const SizedBox(height: 16), PrimaryAction(label: 'Scan this field', icon: Icons.videocam_outlined, onPressed: () => navigateTo(context, const NewScanScreen()))])); }
